name: config

on:
  workflow_call:
    outputs:
      go_version:
        value: ${{ jobs.conf.outputs.go_version }}
      cosign_version:
        value: ${{ jobs.conf.outputs.cosign_version }}
      max_vuln_severity:
        value: ${{ jobs.conf.outputs.max_vuln_severity }}
      registry_uri:
        value: ${{ jobs.conf.outputs.registry_uri }}
      image_uri:
        value: ${{ jobs.conf.outputs.image_uri }}
      id_provider:
        value: ${{ jobs.conf.outputs.id_provider }}
      service_account:
        value: ${{ jobs.conf.outputs.service_account }}
      kms_key:
        value: ${{ jobs.conf.outputs.kms_key }}

jobs:

  conf:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      GO_VERSION: ^1.20
      COSIGN_VERSION: v1.13.1
      MAX_VULN_SEVERITY: 'CRITICAL,HIGH'
      REGISTRY_URI: us-west1-docker.pkg.dev
      IMAGE_URI: us-west1-docker.pkg.dev/s3cme1/artomator/artomator
      ID_PROVIDER: projects/595203407878/locations/global/workloadIdentityPools/artomator-github-pool/providers/github-provider
      SERVICE_ACCOUNT: artomator-github-actions-user@s3cme1.iam.gserviceaccount.com
      KMS_KEY: gcpkms://projects/s3cme1/locations/global/keyRings/artomator-signer-ring/cryptoKeys/artomator-signer/cryptoKeyVersions/1

    outputs:
      go_version: ${{ steps.conf.outputs.go_version }}
      cosign_version: ${{ steps.conf.outputs.cosign_version }}
      max_vuln_severity: ${{ steps.conf.outputs.max_vuln_severity }}
      registry_uri: ${{ steps.conf.outputs.registry_uri }}
      image_uri: ${{ steps.conf.outputs.image_uri }}
      id_provider: ${{ steps.conf.outputs.id_provider }}
      service_account: ${{ steps.conf.outputs.service_account }}
      kms_key: ${{ steps.conf.outputs.kms_key }}
    steps:
    
    - name: Export Config
      id: conf
      run: |
        echo "go_version=${{ env.GO_VERSION }}" >> $GITHUB_OUTPUT
        echo "cosign_version=${{ env.COSIGN_VERSION }}" >> $GITHUB_OUTPUT
        echo "max_vuln_severity=${{ env.MAX_VULN_SEVERITY }}" >> $GITHUB_OUTPUT
        echo "registry_uri=${{ env.REGISTRY_URI }}" >> $GITHUB_OUTPUT
        echo "image_uri=${{ env.IMAGE_URI }}" >> $GITHUB_OUTPUT
        echo "id_provider=${{ env.ID_PROVIDER }}" >> $GITHUB_OUTPUT
        echo "service_account=${{ env.SERVICE_ACCOUNT }}" >> $GITHUB_OUTPUT
        echo "kms_key=${{ env.KMS_KEY }}" >> $GITHUB_OUTPUT
