name: image

on:
  workflow_call:
    inputs:
      go_version:
        description: 'Go version to use'
        type: string
        required: true
      syft_version:
        description: 'The version of syft to use'
        required: true
        type: string
      cosign_version:
        description: 'The version of cosign to use'
        required: true
        type: string
      registry:
        description: 'Artifact Registry URI'
        required: true
        type: string
      id_provider:
        description: 'OIDC provider'
        required: true
        type: string
      service_account:
        description: 'Email of the service account'
        required: true
        type: string
      image:
        description: 'Image URI without the label or sha'
        required: true
        type: string
      max_vuln_severity:
        description: 'Maximum vulnerability severity to allow'
        type: string
        required: true
      key:
        required: true
        description: 'KMS key path'
        type: string
    outputs:
      digest:
        description: "Digest of the published image"
        value: ${{ jobs.image.outputs.digest }}

permissions:
  contents: read

jobs:

  image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      security-events: write
    outputs:
      digest: ${{ steps.image.outputs.digest }}
    steps:

    - name: Checkout Code
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9  # v3.5.3

    - name: Setup Go
      uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753  # v4.0.1
      with:
        go-version: ${{ inputs.go_version }}
    
    - name: Cache Modules
      uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8  # v3.3.1
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Tidy Modules
      run: |
        go mod tidy
        go mod vendor
    
    - name: Capture Version
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    
    - id: auth
      name: Get GCP token
      uses: google-github-actions/auth@35b0e87d162680511bf346c299f71c9c5c379033  # v1.1.1
      with:
          token_format: "access_token"
          workload_identity_provider: ${{ inputs.id_provider }}
          service_account: ${{ inputs.service_account }}
    
    - name: Define Metadata
      id: meta
      uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175  # v4.6.0
      with:
        images: |
          ${{ inputs.image }}
        tags: |
          type=raw,enable=true,value=${{ env.RELEASE_VERSION }}
          type=raw,enable=true,value=${{ env.GITHUB_SHA }}
    
    - name: Registry Auth
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc  # v2.2.0
      with:
        registry: ${{ inputs.registry }}
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
    
    - name: Push Image
      id: push
      uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825  # v4.1.1
      with:
        file: deployment/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Export Digest
      id: digest
      run: |
        echo "IMAGE_DIGEST=${{ inputs.image }}@${{ steps.push.outputs.digest }}" >> $GITHUB_ENV
        echo "DIGEST_TAG=$(echo ${{ steps.push.outputs.digest }} | tr : -)" >> $GITHUB_ENV

    - name: Scan Image
      uses: aquasecurity/trivy-action@41f05d9ecffa2ed3f1580af306000f734b733e54  # v0.11.2
      with:
        image-ref: ${{ env.IMAGE_DIGEST }}
        vuln-type: 'os,library'
        format: sarif
        output: trivy-results.sarif
        hide-progress: true
        timeout: '10m'
        exit-code: '1'
        severity: "${{ inputs.max_vuln_severity }}"
      env:
        GOOGLE_APPLICATION_CREDENTIAL: ${{ steps.auth.outputs.access_token }}

    - name: Upload Results
      uses: github/codeql-action/upload-sarif@1245696032ecf7d39f87d54daa406e22ddf769a8  # v.2.13.3
      with:
        sarif_file: trivy-results.sarif

    - name: Install Syft
      uses: anchore/sbom-action/download-syft@4d571ad1038a9cc29d676154ef265ab8f9027042  # v0.14.2
      with:
        syft-version: ${{ inputs.syft_version }}

    - name: Create SBOM
      run: |
        syft login ${{ inputs.registry }} \
          -u oauth2accesstoken \
          -p ${{ steps.auth.outputs.access_token }}
        syft -q packages \
          -o spdx-json ${{ env.IMAGE_DIGEST }} | \
          jq --compact-output > sbom.spdx

    - name: Install Cosign
      uses: sigstore/cosign-installer@dd6b2e2b610a11fd73dd187a43d57cc1394e35f9  # v3.0.5
      with:
        cosign-release: ${{ inputs.cosign_version }}

    - name: Auth Cosign
      run: |
        cosign version
        cosign login ${{ inputs.registry }} \
          --username=oauth2accesstoken \
          --password=${{ steps.auth.outputs.access_token }}

    - name: Upload SBOM
      run: |
        cosign upload blob \
          -f sbom.spdx \
          -a sha=${{ github.sha }} \
          -a run_id=${{ github.run_id }} \
          -a run_attempt=${{ github.run_attempt }} \
          -a version=${{ env.RELEASE_VERSION }} \
          "${{ inputs.image }}:${{ env.DIGEST_TAG }}.sbom"

    - name: Sign Image
      run: |
        cosign sign --yes \
            --tlog-upload=false \
            --key ${{ inputs.key }} \
            -a sha=${{ github.sha }} \
            -a run_id=${{ github.run_id }} \
            -a run_attempt=${{ github.run_attempt }} \
            -a version=${{ env.RELEASE_VERSION }} \
            ${{ env.IMAGE_DIGEST }}

    - name: Export Digest
      id: image
      run: |
        echo "digest=${{ env.IMAGE_DIGEST }}" >> $GITHUB_OUTPUT
