name: push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  config:
    uses: ./.github/workflows/config.yaml

  test:
    uses: ./.github/workflows/test.yaml
    needs: config
    with:
      go_version: ${{ needs.config.outputs.go_version }}
      max_vuln_severity: ${{ needs.config.outputs.max_vuln_severity }}
