name: publish

on:  
  push:
    tags:
      - 'v*.*.*'

jobs:

  config:
    uses: ./.github/workflows/config.yaml
      
  test:
    uses: ./.github/workflows/test.yaml
    needs: config
    with:
      go_version: ${{ needs.config.outputs.go_version }}
      max_vuln_severity: ${{ needs.config.outputs.max_vuln_severity }}

  image:
    uses: ./.github/workflows/image.yaml
    needs: 
    - config
    - test
    with:
      registry: ${{ needs.config.outputs.registry_uri }}
      image: ${{ needs.config.outputs.image_uri }}
      id_provider: ${{ needs.config.outputs.id_provider }}
      service_account: ${{ needs.config.outputs.service_account }}
      go_version: ${{ needs.config.outputs.go_version }}
      max_vuln_severity: ${{ needs.config.outputs.max_vuln_severity }}
      cosign_version: ${{ needs.config.outputs.cosign_version }}
      key: ${{ needs.config.outputs.kms_key }}
      
  slsa:
    uses: ./.github/workflows/slsa.yaml
    needs: 
    - config
    - image
    with:
      image_digest: ${{ needs.image.outputs.digest }}
      auth_provider: ${{ needs.config.outputs.id_provider }}
      auth_user: ${{ needs.config.outputs.service_account }}
      cosign_version: ${{ needs.config.outputs.cosign_version }}
