name: publish

on:  
  push:
    tags:
      - 'v*.*.*'

jobs:

  test:
    uses: ./.github/workflows/test.yaml

  image:
    uses: ./.github/workflows/image.yaml
    needs: test
    with:
      registry: us-west1-docker.pkg.dev
      id_provider: projects/799736955886/locations/global/workloadIdentityPools/artomator-github-pool/providers/github-provider
      service_account: artomator-github-actions-user@cloudy-demos.iam.gserviceaccount.com
      image: us-west1-docker.pkg.dev/cloudy-demos/artomator/artomator

  sign:
    uses: ./.github/workflows/sign.yaml
    needs: image
    with:
      registry: us-west1-docker.pkg.dev
      id_provider: projects/799736955886/locations/global/workloadIdentityPools/artomator-github-pool/providers/github-provider
      service_account: artomator-github-actions-user@cloudy-demos.iam.gserviceaccount.com
      key: gcpkms://projects/cloudy-demos/locations/global/keyRings/artomator-signer-ring/cryptoKeys/artomator-signer/cryptoKeyVersions/1
      digest: ${{ needs.image.outputs.digest }}

