name: publish

on:  
  push:
    tags:
      - 'v*.*.*'

jobs:

  test:
    uses: ./.github/workflows/test.yaml

  image:
    uses: ./.github/workflows/image.yaml
    needs: test
    with:
      registry: us-west1-docker.pkg.dev
      id_provider: projects/799736955886/locations/global/workloadIdentityPools/artomator-github-pool/providers/github-provider
      service_account: artomator-github-actions-user@cloudy-demos.iam.gserviceaccount.com
      image: us-west1-docker.pkg.dev/cloudy-demos/artomator/artomator


  # sign:
  #   uses: ./.github/workflows/sign.yaml
  #   needs: image
  #   secrets:
  #     registry: ${{ secrets.REGISTRY_URI }}
  #     id_provider: ${{ secrets.ID_PROVIDER }}
  #     service_account: ${{ secrets.SERVICE_ACCOUNT }}
  #     key: ${{ secrets.KMS_KEY }}
  #   with:
  #     digest: ${{ needs.image.outputs.digest }}

