name: release

on:  
  push:
    tags:
      - 'v*.*.*'

jobs:

  config:
    uses: ./.github/workflows/config.yaml
    permissions:
      contents: read
      
  test:
    uses: ./.github/workflows/test.yaml
    needs: config
    permissions:
      contents: read
      security-events: write
    with:
      go_version: ${{ needs.config.outputs.go_version }}
      max_vuln_severity: ${{ needs.config.outputs.max_vuln_severity }}

  image:
    uses: ./.github/workflows/image.yaml
    needs: 
    - config
    - test
    permissions:
      contents: read
      id-token: write
      security-events: write
    with:
      registry: ${{ needs.config.outputs.registry_uri }}
      image: ${{ needs.config.outputs.image_uri }}
      id_provider: ${{ needs.config.outputs.id_provider }}
      service_account: ${{ needs.config.outputs.service_account }}
      go_version: ${{ needs.config.outputs.go_version }}
      max_vuln_severity: ${{ needs.config.outputs.max_vuln_severity }}
      cosign_version: ${{ needs.config.outputs.cosign_version }}
      key: ${{ needs.config.outputs.kms_key }}
      syft_version: ${{ needs.config.outputs.syft_version }}
      
  slsa:
    uses: ./.github/workflows/slsa.yaml
    needs: 
    - config
    - image
    permissions:
      actions: read
      contents: read
      id-token: write
      packages: write
      security-events: write
    with:
      image_digest: ${{ needs.image.outputs.digest }}
      auth_provider: ${{ needs.config.outputs.id_provider }}
      auth_user: ${{ needs.config.outputs.service_account }}
