name: sign

on:
  workflow_call:
    inputs:
      registry:
        description: 'Registry to sign image in'
        required: true
        type: string
      image_digest:
        description: 'Fully-qualified image digest to verify (registry/image@sha256:digest)'
        required: true
        type: string
      auth_provider:
        description: 'OIDC provider ID'
        required: true
        type: string
      auth_user:
        description: 'OIDC user ID'
        required: true
        type: string
      cosign_version:
        description: 'The version of cosign to use'
        required: true
        type: string
      key:
        required: true
        description: 'KMS key path'
        type: string

permissions:
  contents: read

jobs:

  sign:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      id-token: write
    steps:

    - id: auth
      name: Auth GCP
      uses: google-github-actions/auth@35b0e87d162680511bf346c299f71c9c5c379033  # v1.1.1
      with:
        token_format: "access_token"
        workload_identity_provider: ${{ inputs.auth_provider }}
        service_account: ${{ inputs.auth_user }}

    - name: Install Cosign
      uses: sigstore/cosign-installer@dd6b2e2b610a11fd73dd187a43d57cc1394e35f9  # v3.0.5
      with:
        cosign-release: ${{ inputs.cosign_version }}

    - name: Auth Cosign
      run: |
        cosign version
        cosign login ${{ inputs.registry }} \
          --username=oauth2accesstoken \
          --password=${{ steps.auth.outputs.access_token }}

    - name: Sign Image
      run: |
        cosign sign --yes \
            --tlog-upload false \
            --key ${{ inputs.key }} \
            --annotations sha=${{ github.sha }} \
            --annotations run_id=${{ github.run_id }} \
            --annotations run_attempt=${{ github.run_attempt }} \
            --annotations version=${GITHUB_REF#refs/*/} \
            ${{ inputs.image_digest }}

    - name: Verify Signature
      run: |
        cosign verify --key ${{ inputs.key }} ${{ inputs.image_digest }}
