name: sign

on:
  workflow_call:
    inputs:
      registry:
        description: 'Registry to sign image in'
        required: true
        type: string
      image_digest:
        description: 'Fully-qualified image digest to verify (registry/image@sha256:digest)'
        required: true
        type: string
      auth_provider:
        description: 'OIDC provider ID'
        required: true
        type: string
      auth_user:
        description: 'OIDC user ID'
        required: true
        type: string
      cosign_version:
        description: 'The version of cosign to use'
        required: true
        type: string
      max_vuln_severity:
        description: 'Maximum vulnerability severity to allow'
        type: string
        required: true
      key:
        required: true
        description: 'KMS key path'
        type: string

permissions:
  contents: read

jobs:

  sign:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      id-token: write
      contents: write
      security-events: write
    steps:

    - id: auth
      name: Auth GCP
      uses: google-github-actions/auth@35b0e87d162680511bf346c299f71c9c5c379033  # v1.1.1
      with:
        token_format: "access_token"
        workload_identity_provider: ${{ inputs.auth_provider }}
        service_account: ${{ inputs.auth_user }}

    - name: Scan Image
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: image
        security-checks: vuln
        image-ref: ${{ inputs.digest }}
        format: sarif
        output: trivy-results.sarif
        hide-progress: true
        timeout: '10m'
        exit-code: '1'
        severity: ${{ inputs.max_vuln_severity }}
      env:
        GOOGLE_APPLICATION_CREDENTIAL: ${{ steps.auth.outputs.access_token }}

    - name: Upload Results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: trivy-results.sarif
        category: trivy-report

    - name: Install Cosign
      uses: sigstore/cosign-installer@dd6b2e2b610a11fd73dd187a43d57cc1394e35f9  # v3.0.5
      with:
        cosign-release: ${{ inputs.cosign_version }}

    - name: Auth Cosign
      run: |
        cosign version
        cosign login ${{ inputs.registry }} \
          --username=oauth2accesstoken \
          --password=${{ steps.auth.outputs.access_token }}

    - name: Sign Image
      run: |
        cosign sign --force --key ${{ inputs.key }} ${{ inputs.digest }}
      env:
        COSIGN_PASSWORD: ${{ steps.auth.outputs.access_token }}

    - name: Gen SBOM
      run: |
        syft -q packages -o spdx-json ${{ inputs.digest }} | jq --compact-output > sbom.spdx
      env:
        COSIGN_PASSWORD: ${{ steps.auth.outputs.access_token }}

    - name: Create Attestation
      run: |
        cosign attest --predicate sbom.spdx --type spdx --key ${{ inputs.key }} ${{ inputs.digest }}
      env:
        COSIGN_PASSWORD: ${{ steps.auth.outputs.access_token }}
      
    - name: Verify Image
      run: |
        cosign verify-attestation --type spdx --key ${{ inputs.key }} ${{ inputs.digest }}
      env:
        COSIGN_PASSWORD: ${{ steps.auth.outputs.access_token }}
